# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Douglas Dexter
title: Software Testing Analyst
email: douglasldexter@gmail.com
website: replicant.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username:
github_username:  replicant-lad
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: douglas-l-dexter
# xing_username:
# pinterest_username:
#youtube_username: 
# googleplus_username:
# orcid_username: 

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Lorem Ipsum

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Lorem Ipsum
        link: github.com/replicant-lad
        # link_text: Project Website
        additional_links:
          - title:  
            icon: 
            url:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Loremmy ipsummy
        description: | # this will include new lines to allow paragraphs
          lorem ipsum

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IDEXX Laboratories
        link: idexx.com
        # link_text: boringcompany.com
        sub_title: Software Testing Analyst
        caption: July 2023 - Present
        quote: >
          lorum ipsum
        description: | # this will include new lines to allow paragraphs
            lorum ipsum

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Colorado at Boulder
        caption: 2014-2018
        sub_title: BA Biochemistry
        quote: >
          lorum ipsum
        description: | # this will include new lines to allow paragraphs
          lorum ipsum

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      lorum ipsum

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
