# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Douglas Dexter
title: Software Testing Analyst
email: douglasldexter@gmail.com
website: replicant.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username:
github_username:  replicant-lad
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: douglas-l-dexter
# xing_username:
# pinterest_username:
#youtube_username: 
# googleplus_username:
# orcid_username: 

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Douglas Dexter and I'm a software testing analyst at IDEXX Laboratories. I have worked over a number of teams constructing robust automated testing solutions for
  CI/CD focused data engineering teams. I am a data nerd at heart and have been working towards building out my toolbelt for an eventual shift into a development position. I have ample experience
  in Python (pytest, boto3, pandas), AWS data handling (S3, Glue, Lambda, Redshift), Snowflake, and working in Agile environments. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Magic the Data Gathering
        link: https://github.com/replicant-lad/magic-the-data-gathering
        #link_text: Project Website
        additional_links:
          - title:  LookerStudio Report
            icon: 
            url: https://lookerstudio.google.com/reporting/65b3b7c3-6e47-429f-b331-ec07cfaabce2
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Example ETL project utilizing Wizards of the Coast's Magic: The Gathering cards as a living data source. Utilizes AWS Lambdas to extract, transform, and load Scryfall's bulk data dumps into a personal database, with a LookerStudio report built as a viewable front-end report.
        description: | # this will include new lines to allow paragraphs
          the system extracts data from Scryfall's daily bulk dumps and transforms it into a structured format before loading it into a MySQL database for easy access and analysis. For ease (and cost) the database only stores the most recognizable format of each individual card. The bulk of the work was done using AWS Lambda functions for extracting and transforming the data into an S3 bucket and then loading into the MySQL database from there. A step function is triggered daily at noon MST through an EventBridge. The project integrates with a boilerplate LookerStudio Report that looks at the total number of cards printed over time, and the greatest card price differences from day-to-day and over the week while allowing you to sort by set legality.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IDEXX Laboratories
        link: idexx.com
        # link_text: boringcompany.com
        sub_title: Software Testing Analyst
        caption: June 2023 - Present
        quote: >
          Sole quality engineer for a flagship data platform serving AI/ML teams through AWS/Snowflake
        description: | # this will include new lines to allow paragraphs
            I was brought onto a high-value high-output team of developers to build out an end-to-end testing suite for their data pipeline. After a year
            the project now intakes data from numerous sources and data types, with more incoming, and the testing suite remains a core part of the development cycle. I work
            within a team of four developers and promote a focus on data quality visibility.

      - layout: left
        title: IDEXX Laboratories
        link: idexx.com
        # link_text: boringcompany.com
        sub_title: Software Engineer in Test
        caption: June 2021 - June 2023
        quote: >
          Lead quality engineer lead for a high priority, fast paced database retirement project.
        description: | # this will include new lines to allow paragraphs
            I started at IDEXX working on a data warehouse retirement team looking to rebuild their infrastructure on AWS and Snowflake. I acted as the solo quality engineer for a 
            team of six developers, and worked alongside an adjacent team building out a testing platform focusing on source-to-target testing. I quickly became a core quality resource,
            and eventually onboarded my replacement for the role as I transitioned to my new position.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Colorado at Boulder
        caption: 2014-2018
        sub_title: BA Biochemistry
        description: | # this will include new lines to allow paragraphs
          My time at CU Boulder was primarily dedicated to attaining a degree in Biochemistry. While I no longer work in the pharmaceutical field my experiences throughout university
          and my-early career gave me deep understanding of complex data systems and meticulous analysis. As a testing analyst and data engineering learner, I leverage those experiences
          to develop efficient solutions. Through the lens of biochemistry I bring a unique perspective to the world of data, bridging the gap between science and the technology that supports it.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my free time I consider myself a hobbyist's hobbyist, moving my focus from hobby to hobby to explore. Some hobbies have become something of a mainstay, though:

      - Thru-Hiking and Camping
      - Ukiyo-e Woodblock Carving
      - Ukulele and Piano
      - Trading Card Games
      - Tabletop RPGs, LARPing


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
